### ISSUE TITLE
Usage recommendations for performance

### ISSUE THREAD

**Issue by smola** [src-d/ml#209]
It would be nice to document some performance hints.

For example, should I use `--persist MEMORY_AND_DISK`? Are there other parameters related to performance?

**Comment by r0mainK** [comment]
@smola agreed, although I think most parameters related to performance will most probably fall in the tuning spark category, as is this one.

Regarding your question, it really depends what data you are using and what machine is running spark. To my knowledge the `--persist` flag only enables **our** caching. We use the a `Cacher` transformer in the code, it basically just calls the spark `persist` method with the storage level specified by this flag, unless it has been omitted in which case it does nothing.

Here is a quick recap of the different spark storage levels:
```
Level                Space used  CPU time  In memory  On disk  Serialized
-------------------------------------------------------------------------
MEMORY_ONLY          High        Low       Y          N        N
MEMORY_ONLY_SER      Low         High      Y          N        Y
MEMORY_AND_DISK      High        Medium    Some       Some     Some
MEMORY_AND_DISK_SER  Low         High      Some       Some     Y
DISK_ONLY            Low         High      N          Y        Y
```
So if you have a ton of RAM and relatively small data, MEMORY_ONLY is good, if you have a ton of data, enough space and a bad CPU, DISK_ONLY might be preferable. I think tests are required to find what works best, however when running on large data this flag should not be ommited, whatever the sotrage level chosen, bc it will avoid looong recomputation.

By the way while researching this question I saw that Spark will sometime cache data automatically after some operations, so in the case this flag is present I think we should also modify the storage level in the spark conf created in `create_spark`.

Also, regarding performance tuning, [this](https://stackoverflow.com/questions/37871194/how-to-tune-spark-executor-number-cores-and-executor-memory) is pretty useful to tune your number of executors, executor memory, etc. and we might wanna add a flag to tune the number of partitions, since it is also pretty linked to the [number of cores available] (https://hackernoon.com/managing-spark-partitions-with-coalesce-and-repartition-4050c57ad5c4)

**Comment by vmarkovtsev** [comment]
@r0mainK Please copy-paste this useful manual to somewhere inside `ml`'s docs and I'll close this.

**Comment by r0mainK** [comment]
Created PR: https://github.com/src-d/ml/pull/217 issue can be closed.
