### ISSUE TITLE
Option to avoid downloading Apache Spark on every install

### ISSUE THREAD

**Issue by bzz** [src-d/ml#233]
Sorry if I'm missing something here, but right now `sourced.ml` library has, what seems to be a [mandatory dependency](https://github.com/src-d/ml/blob/master/requirements.txt#L9) on Apache Spark though `pip`.

As a user of src-d/ml, I would expect this library to let me avoid downloading 188Mb of Apache Spark as a dependency, and instead let me choosing my local Apache Spark installation \w pySpark through `$SPARK_HOME`.

Same way as it's not fetching Tensorflow and libxml2 and just mention them in https://github.com/src-d/ml#installation

**Comment by vmarkovtsev** [comment]
It is impossible to require Tensorflow properly because there are two package flavors - with and without GPU. Thus we have to discard it.

libxml2 is a native dependency, it is impossible to require.

Spark has a well-defined version series and half of ml depends on it. Without, it will not even sucessfully import. Your local Spar installation can be `pip install -e`-ed. `-e` option does the development installation.

**Comment by vmarkovtsev** [comment]
As always, it makes much sense documenting anything :) Thanks for the new use case and I will be happy to merge a PR.
